version: '3.8'
services:
    
    # Application
    app:
        build:
            context: .
            dockerfile: ./dockerfile/app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "database"
        ports:
            - "9001:9000"  
    # Web Server
    web:
        build:
            context: .
            dockerfile: ./dockerfile/web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "app"
        ports:
            - 8000:80
    # Database
    database:
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 33061:3306
    # VueJs npm    
    node: 
        image: node:12.18.2
        working_dir: /var/www
        ports:
        - "8082:8080"
        volumes:
        - ./:/var/www
        command: tail -f /dev/null  
volumes:
    dbdata: